import { Router } from "express";
import authRoutes from "../modules/auth/auth.routes.js";
import userRoutes from "../modules/users/user.routes.js";
import questionBankRoutes from "../modules/question-banks/questionBank.routes.js";
import questionRoutes from "../modules/question-bank/question.routes.js";
import examRoutes from "../modules/exams/exam.routes.js";
import publicExamRoutes from "../modules/public-exams/publicExam.routes.js";
import attemptRoutes from "../modules/attempts/attempt.routes.js";
import antiCheatRoutes from "../modules/anti-cheat/antiCheat.routes.js";
import reportRoutes from "../modules/reports/report.routes.js";
import dashboardRoutes from "../modules/dashboard/dashboard.routes.js";
import auditRoutes from "../modules/audit-logs/auditLog.routes.js";
import settingRoutes from "../modules/settings/setting.routes.js";
const router = Router();
router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/question-banks", questionBankRoutes);
router.use("/questions", questionRoutes);
router.use("/exams", examRoutes);
router.use("/public/exams", publicExamRoutes);
router.use(attemptRoutes);
router.use(antiCheatRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/reports", reportRoutes);
router.use("/audit-logs", auditRoutes);
router.use("/settings", settingRoutes);
export default router;
