import { Router } from "express";
import authRoutes from "../modules/auth/auth.routes.js";
import userRoutes from "../modules/users/user.routes.js";
import departmentRoutes from "../modules/departments/department.routes.js";
import courseRoutes from "../modules/courses/course.routes.js";
import questionRoutes from "../modules/question-bank/question.routes.js";
import examRoutes from "../modules/exams/exam.routes.js";
import attemptRoutes from "../modules/attempts/attempt.routes.js";
import antiCheatRoutes from "../modules/anti-cheat/antiCheat.routes.js";
import reportRoutes from "../modules/reports/report.routes.js";
import auditRoutes from "../modules/audit-logs/auditLog.routes.js";
import settingRoutes from "../modules/settings/setting.routes.js";
const router = Router();
router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/departments", departmentRoutes);
router.use("/courses", courseRoutes);
router.use("/questions", questionRoutes);
router.use("/exams", examRoutes);
router.use(attemptRoutes);
router.use(antiCheatRoutes);
router.use("/reports", reportRoutes);
router.use("/audit-logs", auditRoutes);
router.use("/settings", settingRoutes);
export default router;
