import { Router } from "express";
import * as controller from "./department.controller.js";
import { authenticate } from "../../middlewares/auth.middleware.js";
import { authorizeRoles } from "../../middlewares/role.middleware.js";
import { requirePermission } from "../../middlewares/permission.middleware.js";
import { validate } from "../../middlewares/validate.middleware.js";
import { ROLES } from "../../constants/roles.js";
import { PERMISSIONS } from "../../constants/permissions.js";
import { departmentSchema, departmentUpdateSchema } from "./department.validation.js";
const router = Router();
router.use(authenticate, authorizeRoles(ROLES.SUPER_ADMIN, ROLES.SUB_ADMIN), requirePermission(PERMISSIONS.MANAGE_DEPARTMENTS));
router.route("/").get(controller.list).post(validate({ body: departmentSchema }), controller.create);
router.route("/:id").get(controller.get).patch(validate({ body: departmentUpdateSchema }), controller.update).delete(controller.remove);
export default router;
