export const ANTI_CHEAT_POINTS = Object.freeze({
  RIGHT_CLICK_ATTEMPT: 1, COPY_ATTEMPT: 1, PASTE_ATTEMPT: 1, CUT_ATTEMPT: 1,
  PRINT_ATTEMPT: 2, SAVE_ATTEMPT: 2, FULLSCREEN_EXITED: 2, TAB_SWITCHED: 2,
  WINDOW_BLUR: 2, PAGE_REFRESH_ATTEMPT: 2, BROWSER_BACK_ATTEMPT: 2,
  HEARTBEAT_MISSED: 3, DEVTOOLS_ATTEMPT: 5, DUPLICATE_SESSION_ATTEMPT: 5,
  WEBCAM_PERMISSION_DENIED: 5, WEBCAM_DISABLED: 5, LONG_AWAY_TIME: 5,
  WINDOW_FOCUS: 0, SNAPSHOT_CAPTURED: 0, SCREENSHOT_CAPTURED: 0,
  AUTO_SUBMIT_TRIGGERED: 0, MANUAL_SUBMIT: 0, TIMER_EXPIRED: 0
});
export const ANTI_CHEAT_EVENTS = Object.keys(ANTI_CHEAT_POINTS);
export const SEVERITIES = ["LOW", "MEDIUM", "HIGH", "CRITICAL"];
export const SYSTEM_ACTIONS = ["LOG_ONLY", "WARNING", "FINAL_WARNING", "AUTO_SUBMIT", "LOCK_ATTEMPT"];
