export const PERMISSIONS = Object.freeze({
  VIEW_DASHBOARD: "VIEW_DASHBOARD",
  VIEW_USERS: "VIEW_USERS",
  MANAGE_USERS: "MANAGE_USERS",
  MANAGE_EXAMINERS: "MANAGE_EXAMINERS",
  MANAGE_CANDIDATES: "MANAGE_CANDIDATES",
  VIEW_ALL_EXAMS: "VIEW_ALL_EXAMS",
  VIEW_ALL_ATTEMPTS: "VIEW_ALL_ATTEMPTS",
  VIEW_ALL_REPORTS: "VIEW_ALL_REPORTS",
  VIEW_ANTI_CHEAT_REPORTS: "VIEW_ANTI_CHEAT_REPORTS",
  VIEW_REPORTS: "VIEW_REPORTS",
  VIEW_AUDIT_LOGS: "VIEW_AUDIT_LOGS",
  MANAGE_PLATFORM_SETTINGS: "MANAGE_PLATFORM_SETTINGS",
  MANAGE_SETTINGS: "MANAGE_SETTINGS",
  DISABLE_EXAMS: "DISABLE_EXAMS",
  MANAGE_DEPARTMENTS: "MANAGE_DEPARTMENTS",
  MANAGE_COURSES: "MANAGE_COURSES",
  BLOCK_USERS: "BLOCK_USERS",
  RESET_USER_PASSWORDS: "RESET_USER_PASSWORDS"
});

export const PERMISSION_VALUES = Object.values(PERMISSIONS);
