export const PERMISSIONS = Object.freeze({
  MANAGE_USERS: "MANAGE_USERS",
  MANAGE_EXAMINERS: "MANAGE_EXAMINERS",
  MANAGE_CANDIDATES: "MANAGE_CANDIDATES",
  MANAGE_DEPARTMENTS: "MANAGE_DEPARTMENTS",
  MANAGE_COURSES: "MANAGE_COURSES",
  VIEW_REPORTS: "VIEW_REPORTS",
  VIEW_AUDIT_LOGS: "VIEW_AUDIT_LOGS",
  MANAGE_SETTINGS: "MANAGE_SETTINGS",
  BLOCK_USERS: "BLOCK_USERS",
  RESET_USER_PASSWORDS: "RESET_USER_PASSWORDS"
});

export const PERMISSION_VALUES = Object.values(PERMISSIONS);
