export const USER_STATUSES = ["ACTIVE", "BLOCKED", "SUSPENDED", "DELETED"];
export const RESOURCE_STATUSES = ["ACTIVE", "INACTIVE", "DELETED"];
export const EXAM_STATUSES = ["DRAFT", "SCHEDULED", "ACTIVE", "CLOSED", "CANCELLED", "ARCHIVED"];
export const ATTEMPT_STATUSES = ["NOT_STARTED", "IN_PROGRESS", "SUBMITTED", "AUTO_SUBMITTED", "LOCKED", "FLAGGED", "CANCELLED", "EXPIRED"];
export const SUBMISSION_TYPES = ["MANUAL", "TIMER_EXPIRED", "ANTI_CHEAT_AUTO_SUBMIT", "ADMIN_FORCE_SUBMIT"];
