import { Router } from "express";
import * as controller from "./attempt.controller.js";
import { authenticate } from "../../middlewares/auth.middleware.js";
import { optionalAuthenticate } from "../../middlewares/optionalAuth.middleware.js";
import { authorizeRoles } from "../../middlewares/role.middleware.js";
import { validate } from "../../middlewares/validate.middleware.js";
import { ROLES } from "../../constants/roles.js";
import { startSchema, answerSchema, submitSchema, heartbeatSchema } from "./attempt.validation.js";
const router = Router();
router.get("/attempts", authenticate, authorizeRoles(ROLES.SUPER_ADMIN, ROLES.SUB_ADMIN, ROLES.EXAMINER), controller.list);
router.get("/candidate/exams", authenticate, authorizeRoles(ROLES.CANDIDATE), controller.candidateExams);
router.get("/candidate/exams/:examId/instructions", authenticate, authorizeRoles(ROLES.CANDIDATE), controller.instructions);
router.post("/exams/:examId/start", authenticate, authorizeRoles(ROLES.CANDIDATE), validate({ body: startSchema }), controller.start);
router.get("/attempts/:attemptId", optionalAuthenticate, controller.get);
router.post("/attempts/:attemptId/save-answer", optionalAuthenticate, validate({ body: answerSchema }), controller.save);
router.post("/attempts/:attemptId/heartbeat", optionalAuthenticate, validate({ body: heartbeatSchema }), controller.heartbeat);
router.post("/attempts/:attemptId/submit", optionalAuthenticate, validate({ body: submitSchema }), controller.submit);
router.get("/attempts/:attemptId/result", optionalAuthenticate, controller.result);
export default router;
