import { Router } from "express";
import * as controller from "./antiCheat.controller.js";
import { authenticate } from "../../middlewares/auth.middleware.js";
import { optionalAuthenticate } from "../../middlewares/optionalAuth.middleware.js";
import { validate } from "../../middlewares/validate.middleware.js";
import { upload } from "../../middlewares/upload.middleware.js";
import { logEventSchema } from "./antiCheat.validation.js";
const router = Router();
router.post("/attempts/:attemptId/anti-cheat/log", optionalAuthenticate, validate({ body: logEventSchema }), controller.log);
router.post("/attempts/:attemptId/snapshot", optionalAuthenticate, upload.single("file"), controller.snapshot);
router.post("/attempts/:attemptId/screenshot", optionalAuthenticate, upload.single("file"), controller.screenshot);
router.get("/attempts/:attemptId/anti-cheat/logs", optionalAuthenticate, controller.attemptLogs);
router.get("/exams/:examId/anti-cheat/reports", authenticate, controller.reports);
router.get("/anti-cheat/logs/:logId/evidence-url", authenticate, controller.evidenceUrl);
export default router;
