import { Router } from "express";
import * as controller from "./exam.controller.js";
import { authenticate } from "../../middlewares/auth.middleware.js";
import { authorizeRoles } from "../../middlewares/role.middleware.js";
import { validate } from "../../middlewares/validate.middleware.js";
import { ROLES } from "../../constants/roles.js";
import { examSchema, examUpdateSchema, assignCandidatesSchema, inviteListSchema, createInviteSchema } from "./exam.validation.js";
const router = Router();
router.use(authenticate);
router.get("/", controller.list);
router.get("/:id", controller.get);
router.post("/", authorizeRoles(ROLES.EXAMINER), validate({ body: examSchema }), controller.create);
router.patch("/:id", authorizeRoles(ROLES.EXAMINER), validate({ body: examUpdateSchema }), controller.update);
router.post("/:id/archive", authorizeRoles(ROLES.EXAMINER), controller.remove);
router.delete("/:id", authorizeRoles(ROLES.EXAMINER), controller.remove);
router.delete("/:id/permanent", authorizeRoles(ROLES.EXAMINER), controller.hardDelete);
router.post("/:id/publish", authorizeRoles(ROLES.EXAMINER), controller.publish);
router.post("/:id/unpublish", authorizeRoles(ROLES.EXAMINER), controller.unpublish);
router.post("/:id/close", authorizeRoles(ROLES.EXAMINER), controller.close);
router.post("/:id/disable", authorizeRoles(ROLES.SUPER_ADMIN, ROLES.SUB_ADMIN), controller.disable);
router.post("/:id/regenerate-access-code", authorizeRoles(ROLES.EXAMINER), controller.regenerateAccessCode);
router.post("/:id/regenerate-link", authorizeRoles(ROLES.EXAMINER), controller.regenerateLink);
router.get("/:id/access-info", authorizeRoles(ROLES.SUPER_ADMIN, ROLES.SUB_ADMIN, ROLES.EXAMINER), controller.accessInfo);
router.get("/:id/attempts", authorizeRoles(ROLES.SUPER_ADMIN, ROLES.SUB_ADMIN, ROLES.EXAMINER), controller.attempts);
router.get("/:id/reports", authorizeRoles(ROLES.SUPER_ADMIN, ROLES.SUB_ADMIN, ROLES.EXAMINER), controller.reports);
router.post("/:id/assign-candidates", authorizeRoles(ROLES.SUPER_ADMIN, ROLES.SUB_ADMIN, ROLES.EXAMINER), validate({ body: assignCandidatesSchema }), controller.assign);
router.get("/:id/candidates", authorizeRoles(ROLES.SUPER_ADMIN, ROLES.SUB_ADMIN, ROLES.EXAMINER), controller.candidates);
router.get("/:id/invites", authorizeRoles(ROLES.SUPER_ADMIN, ROLES.SUB_ADMIN, ROLES.EXAMINER), controller.invites);
router.post("/:id/invites", authorizeRoles(ROLES.SUPER_ADMIN, ROLES.SUB_ADMIN, ROLES.EXAMINER), validate({ body: createInviteSchema }), controller.createInvites);
router.put("/:id/invites", authorizeRoles(ROLES.SUPER_ADMIN, ROLES.SUB_ADMIN, ROLES.EXAMINER), validate({ body: inviteListSchema }), controller.replaceInvites);
router.get("/:id/invites/export", authorizeRoles(ROLES.SUPER_ADMIN, ROLES.SUB_ADMIN, ROLES.EXAMINER), controller.exportInvites);
router.delete("/:id/invites/:inviteId", authorizeRoles(ROLES.SUPER_ADMIN, ROLES.SUB_ADMIN, ROLES.EXAMINER), controller.removeInvite);
export default router;
