import { Router } from "express";
import * as controller from "./exam.controller.js";
import { authenticate } from "../../middlewares/auth.middleware.js";
import { authorizeRoles } from "../../middlewares/role.middleware.js";
import { validate } from "../../middlewares/validate.middleware.js";
import { ROLES } from "../../constants/roles.js";
import { examSchema, examUpdateSchema, assignCandidatesSchema } from "./exam.validation.js";
const router = Router();
router.use(authenticate);
router.get("/", controller.list);
router.get("/:id", controller.get);
router.post("/", authorizeRoles(ROLES.SUPER_ADMIN, ROLES.EXAMINER), validate({ body: examSchema }), controller.create);
router.patch("/:id", authorizeRoles(ROLES.SUPER_ADMIN, ROLES.EXAMINER), validate({ body: examUpdateSchema }), controller.update);
router.delete("/:id", authorizeRoles(ROLES.SUPER_ADMIN, ROLES.EXAMINER), controller.remove);
router.post("/:id/publish", authorizeRoles(ROLES.SUPER_ADMIN, ROLES.EXAMINER), controller.publish);
router.post("/:id/close", authorizeRoles(ROLES.SUPER_ADMIN, ROLES.EXAMINER), controller.close);
router.post("/:id/assign-candidates", authorizeRoles(ROLES.SUPER_ADMIN, ROLES.EXAMINER), validate({ body: assignCandidatesSchema }), controller.assign);
router.get("/:id/candidates", authorizeRoles(ROLES.SUPER_ADMIN, ROLES.EXAMINER), controller.candidates);
export default router;
